# -*- mode: python ; coding: utf-8 -*-

EXCLUDES = [
    'av',
    'boto3',
    'botocore',
    'cv2',
    'datasets',
    'matplotlib',
    'nltk',
    'numpy',
    'onnxruntime',
    'openpyxl',
    'opentelemetry',
    'pandas',
    'PIL',
    'py',
    'pyarrow',
    'pygments',
    'pytest',
    'scipy',
    'sklearn',
    'sqlalchemy',
    'tensorflow',
    'tkinter',
    'torch',
    'transformers',
    'win32com',
]

a = Analysis(
    ['fb_archiver.py'],
    pathex=[],
    binaries=[],
    datas=[('fb_archiv_html_viewer.html', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='fb_archiver',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
